# Generated by Django 3.2 on 2023-02-27 20:09

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='İstifadəçi adı')),
                ('surname', models.CharField(blank=True, max_length=40, null=True, verbose_name='İstifadəçi soyadı')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=services.uploader.Uploader.upload_images_for_user)),
                ('slug', models.SlugField(unique=True)),
                ('activation_code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('password_reset_code', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'CustomUser',
                'verbose_name_plural': 'Custom Users',
                'ordering': ['-timestamp'],
            },
        ),
    ]
