# Generated by Django 3.2 on 2023-03-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20230312_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_restaurant_owner',
            field=models.BooleanField(default=False),
        ),
    ]
