countries = {
"Azerbaijan": "Azərbaycan",
"Turkey": "Türkiyə",
"Russia": "Rusiya",
"İtaly": "İtaliya",
"Spain": "İspaniya",
"Finland": "Finlandiya",
"Poland": "Polşa",
"Greece": "Yunanıstan",
"France": "Fransa",
"Portugal": "Portuqaliya",
"Germany": "Almaniya",
"Argentina": "Argentina",
"Australia": "Avstraliya",
"Bahamas": "Baham adaları",
"Belgium": "Belçika",
"Bulgaria": "Bolqarıstan",
"Brazil": "Braziliya",
"Bahrain": "Bəhreyn",
"South Korea": "Cənubi Koreya",
"Czech": "Çexiya",
"Chile": "Çili",
'Canada': "Kanada",
"Danimark": "Danimarka",
"Georgia": "Gürcüstan",
"İndia": "Hindistan",
"Croatia": "Xorvatiya",
"Indonesia": "İndoneziya",
"Iran": "İran",
"Ireland": "İrlandiya",
"Israel": "İsrail",
"Sweden": "İsveç",
"Switzerland": "İsveçrə",
"Colombia": "Kolumbiya",
"Costa Rica": "Kosta-Rika",
"Kuwait": "Küveyt",
"Kazakhstan": "Qazaxıstan",
"Kyrgyzstan": "Qırğızıstan",
"Hungary": "Macarıstan",
"Luxembourg": "Lüksemburq",
"New Zealand": "Yeni Zelandiya",
"Japan": "Yaponiya",
"Vietnam": "Vyetnam",
"Vatican": "Vatikan",
"Uruguay": "Uruqvay",
"Ukraine": "Ukrayna",
"Turkmenistan": "Türkmənistan",
"China": "Çin",
"Thailand": "Tailand",
"Tajikistan": "Tacikistan",
"Sri Lanka": "Şri-Lanka",
"UAE": "BƏƏ",
"Slovenia": "Sloveniya",
"Slovakia": "Slovakiya",
"Singapore": "Sinqapur",
"Saudi Arabia": "Səudiyyə Ərəbistanı",
"Serbia": "Serbiya",
"Romania": "Ruminiya",
"Peru": "Peru",
"Paraguay": "Paraqvay",
"Panama": "Panama",
"Pakistan": "Pakistan",
"Uzbekistan": "Özbəkistan",
"Norway": "Norveç",
"Netherlands": "Niderland",
"Nepal": "Nepal",
"Mongolia": "Monqolustan",
"Egypt": "Misir",
"Moldova": "Moldova",
"Mexico": "Meksika",
"Malta": "Malta",
"Maldives Islands": "Maldiv adaları",
"North Macedonia": "Şimali Makedoniya",
"Madagascar": "Madaqaskar",

}