# Generated by Django 3.2 on 2023-02-12 22:25

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('type_r', models.CharField(choices=[('Fast-food', 'Fast-food'), ('Milli', 'Milli'), ('Ailevi', 'Ailevi'), ('Business-lunch', 'Business-lunch'), ('Sirniyyat', 'Sirniyyat'), ('Vegetarian', 'Vegetarian'), ('Self-service', 'Self-service'), ('Club', 'Club')], max_length=100)),
                ('rating', models.IntegerField()),
                ('menu', models.FileField(upload_to=services.uploader.Uploader.upload_menu_to_restaurants)),
                ('images', models.ImageField(upload_to=services.uploader.Uploader.upload_images_to_restaurants)),
                ('number', models.TextField()),
                ('location', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
