# Generated by Django 3.2 on 2023-02-12 22:35

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_restaurants_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurants',
            options={'ordering': ('-created_at',), 'verbose_name': 'Restaurant', 'verbose_name_plural': 'Restaurants'},
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='images',
            field=models.FileField(upload_to=services.uploader.Uploader.upload_images_to_restaurants),
        ),
    ]
