# Generated by Django 3.2 on 2023-02-13 23:57

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20230213_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='CooperationCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=services.uploader.Uploader.upload_images_for_cooperation)),
            ],
            options={
                'verbose_name': 'Cooperation-Company',
                'verbose_name_plural': 'Cooperation-Companies',
                'ordering': ('-created_at',),
            },
        ),
    ]
