# Generated by Django 3.2 on 2023-02-14 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_cooperationcompanies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('restaurants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.restaurants')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
