# Generated by Django 3.2 on 2023-02-14 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countries',
            name='restaurants',
        ),
    ]
