# Generated by Django 3.2 on 2023-02-14 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_countries_restaurants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='country',
        ),
    ]
