# Generated by Django 3.2 on 2023-02-14 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_restaurants_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='country_of_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.countries'),
        ),
    ]
