# Generated by Django 3.2 on 2023-02-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_restaurants_country_of_restaurant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countries',
            options={'ordering': ('-created_at',), 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AddField(
            model_name='countries',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
