# Generated by Django 3.2 on 2023-02-15 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20230216_0206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.RemoveField(
            model_name='countries',
            name='city',
        ),
        migrations.AlterField(
            model_name='cities',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.countries'),
        ),
    ]
