# Generated by Django 3.2 on 2023-02-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20230216_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='seats',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
