# Generated by Django 3.2 on 2023-02-23 22:22

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_alter_restaurantmenu_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmenu',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to=services.uploader.Uploader.upload_images_for_menu),
        ),
    ]
