# Generated by Django 3.2 on 2023-02-24 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0022_restaurantmenu_qr_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantmenu',
            old_name='qr_code',
            new_name='qr_code_x',
        ),
    ]
