# Generated by Django 3.2 on 2023-02-25 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_restaurantmenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='qrcode_image',
        ),
    ]
