# Generated by Django 3.2 on 2023-02-26 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
