# Generated by Django 3.2 on 2023-02-27 17:17

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_auto_20230227_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='replycomment',
            name='level',
            field=models.PositiveIntegerField(default='5', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='replycomment',
            name='lft',
            field=models.PositiveIntegerField(default='5', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='replycomment',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='booking.replycomment'),
        ),
        migrations.AddField(
            model_name='replycomment',
            name='rght',
            field=models.PositiveIntegerField(default='5', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='replycomment',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default='5', editable=False),
            preserve_default=False,
        ),
    ]
