# Generated by Django 3.2 on 2023-02-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_auto_20230227_2117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReplyComment',
        ),
    ]
