# Generated by Django 3.2 on 2023-02-27 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0033_replycomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReplyComment',
        ),
    ]
