# Generated by Django 3.2 on 2023-02-27 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0034_delete_replycomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
