# Generated by Django 3.2 on 2023-02-28 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0036_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='available_seats',
        ),
    ]
