# Generated by Django 3.2 on 2023-02-28 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0040_auto_20230228_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.restaurants'),
        ),
    ]
