# Generated by Django 3.2 on 2023-02-28 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0041_likes_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_likes', to='booking.restaurants'),
        ),
    ]
