# Generated by Django 3.2 on 2023-03-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0044_restaurants_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='available_seats',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
