# Generated by Django 3.2 on 2023-03-06 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0048_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='count_of_children',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='rating',
            field=models.IntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
