# Generated by Django 3.2 on 2023-03-06 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0049_auto_20230306_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='rating',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
