# Generated by Django 3.2 on 2023-03-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0051_alter_restaurants_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve',
            old_name='count_of_adult',
            new_name='count_of_guest',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='count_of_children',
        ),
        migrations.AddField(
            model_name='reserve',
            name='date',
            field=models.DateField(default='2022-12-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserve',
            name='notes',
            field=models.TextField(default='2022-12-12'),
            preserve_default=False,
        ),
    ]
