# Generated by Django 3.2 on 2023-03-06 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0053_alter_reserve_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='restaurant',
            field=models.ForeignKey(default='34', on_delete=django.db.models.deletion.CASCADE, to='booking.restaurants'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserve',
            name='user',
            field=models.ForeignKey(default='34', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
