# Generated by Django 3.2 on 2023-03-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0056_auto_20230307_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='date',
            field=models.DateField(),
        ),
    ]
