# Generated by Django 3.2 on 2023-03-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0060_auto_20230307_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='reserved',
            field=models.BooleanField(default=True),
        ),
    ]
