# Generated by Django 3.2 on 2023-03-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0066_alter_restaurants_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='wishlist',
        ),
    ]
