# Generated by Django 3.2 on 2023-03-10 20:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0069_remove_comment_likers'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likers',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
