# Generated by Django 3.2 on 2023-03-11 10:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0070_comment_likers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likers',
            field=models.ManyToManyField(blank=True, default=None, related_name='likers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
