# Generated by Django 3.2 on 2023-03-11 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0071_auto_20230311_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
