# Generated by Django 3.2 on 2023-03-11 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0073_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='user',
        ),
    ]
