# Generated by Django 3.2 on 2023-03-11 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0074_remove_likes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='accounts.myuser'),
            preserve_default=False,
        ),
    ]
