# Generated by Django 3.2 on 2023-03-11 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0076_auto_20230312_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='user',
        ),
    ]
