# Generated by Django 3.2 on 2023-03-12 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0081_alter_restaurantimages_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantmenu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.restaurants'),
        ),
    ]
