# Generated by Django 3.2 on 2023-03-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0083_auto_20230314_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
