# Generated by Django 3.2 on 2023-03-15 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0084_alter_reserve_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='hour',
        ),
    ]
