# Generated by Django 3.2 on 2023-03-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0086_restaurants_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='type_r',
            field=models.CharField(blank=True, choices=[('Fast-food', 'Fast-food'), ('Milli', 'Milli'), ('Ailəvi', 'Ailəvi'), ('Business-lunch', 'Business-lunch'), ('Şirniyyat', 'Şirniyyat'), ('Vegetarian', 'Vegetarian'), ('Özünə xidmət', 'Özünə xidmət'), ('Klub', 'Klub')], max_length=100, null=True),
        ),
    ]
