# Generated by Django 3.2 on 2023-03-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0087_alter_restaurants_type_r'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
