# Generated by Django 3.2 on 2023-03-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0088_restaurants_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='phone_number',
        ),
    ]
