# Generated by Django 3.2 on 2023-03-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0089_remove_restaurants_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='number',
            field=models.CharField(max_length=200),
        ),
    ]
