# Generated by Django 3.2 on 2023-03-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0090_auto_20230322_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='has_permission',
            field=models.BooleanField(default=False),
        ),
    ]
