# Generated by Django 3.2 on 2023-03-28 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0098_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.restaurants'),
        ),
    ]
