# Generated by Django 3.2 on 2023-03-29 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0099_alter_comment_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='closed',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{2}:\\d{2}$')]),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='opened',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{2}:\\d{2}$')]),
        ),
    ]
