# Generated by Django 3.2 on 2023-03-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0100_auto_20230330_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='closed',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='opened',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
