# Generated by Django 3.2 on 2023-03-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0101_auto_20230330_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='closed',
            field=models.TimeField(blank=True, default='None', null=True),
        ),
    ]
